# ! INSTALL REST CLIENT EXTENSION ON VS CODE TO USE THIS FILE FOR TESTING ENDPOINTS
# * CHANGE THE PORT ON ANY FILE WITH HTTP TO YOUR DESIGNATED PORT
@port = 8080
@baseUrl = http://localhost:{{port}}

GET {{baseUrl}}/